export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const UPDATE_SELECTED_CATEGORY = 'UPDATE_SELECTED_CATEGORY';

export const UPDATE_HASHTAGS = 'UPDATE_HASHTAGS';
export const UPDATE_SELECTED_HASHTAGS = 'UPDATE_SELECTED_HASHTAGS';

export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT';

export const GET_PRODUCTS = 'GET_PRODUCTS';

export const GET_FAVORITES = 'GET_FAVORITES';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';

export const SHOW_BARCODE = 'SHOW_BARCODE';
export const SHOW_PRODUCT_LOADING = 'SHOW_PRODUCT_LOADING';
export const SHOW_PRODUCT_NOT_FOUND = 'SHOW_PRODUCT_NOT_FOUND';
