export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const UPDATE_SELECTED_CATEGORY = 'UPDATE_SELECTED_CATEGORY';

export const GET_PRODUCTS = 'GET_PRODUCTS';

export const UPDATE_HASHTAGS = 'UPDATE_HASHTAGS';
