export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const UPDATE_SELECTED_CATEGORY = 'UPDATE_SELECTED_CATEGORY';

export const UPDATE_HASHTAGS = 'UPDATE_HASHTAGS';
export const UPDATE_SELECTED_HASHTAGS = 'UPDATE_SELECTED_HASHTAGS';

export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT';

export const GET_PRODUCTS = 'GET_PRODUCTS';

export const SHOW_BARCODE = 'SHOW_BARCODE';
